[package]
name = "linuxpoc"
version = "0.0.1"
authors = ["Carlo Tomasin <c.tomasin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.4"
dbus = "0.8.4"
#dbus-codegen = "0.5.0"
